print(True and True); print('True'); print("========\n\n")
print(False and True); print('False'); print("========\n\n")
print(1 == 1 and 2 == 1); print('False'); print("========\n\n")
print("test" == "test"); print('True'); print("========\n\n")
print(1 == 1 or 2 != 1); print('True'); print("========\n\n")
print(True and 1 == 1); print('True'); print("========\n\n")
print(False and 0 != 0); print('False'); print("========\n\n")
print(True or 1 == 1); print('True'); print("========\n\n")
print("test" == "testing"); print('False'); print("========\n\n")
print(1 != 0 and 2 == 1); print('False'); print("========\n\n")
print("test" != "testing"); print('True'); print("========\n\n")
print("test" == 1); print('False'); print("========\n\n")
print(not (True and False)); print('True'); print("========\n\n")
print(not (1 == 1 and 0 != 1)); print('False'); print("========\n\n")
print(not (10 == 1 or 1000 == 1000)); print('False'); print("========\n\n")
print(not (1 != 10 or 3 == 4)); print('False'); print("========\n\n")
print(not ("testing" == "testing" and "Zed" == "Cool Guy")); print('True'); print("========\n\n")
print(1 == 1 and (not ("testing" == 1 or 1 == 0))); print('True'); print("========\n\n")
print("chunky" == "bacon" and (not (3 == 4 or 3 == 3))); print('False'); print("========\n\n")
print(3 == 3 and (not ("testing" == "testing" or "Python" == "Fun"))); print('False'); print("========\n\n")
